@startuml C4_Elements
' Reduce complexity by disecting the container level diagram.
' It is not useful to make component diagrams of the entire diagram.

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/release/1-0/C4_Component.puml

LAYOUT_WITH_LEGEND()

Person(user, "User", "The SecHub user")

System_Boundary(sechub, "SecHub") {
	Container(sechub_server, "SecHub Server", "Java, Spring MVC, Tomcat", "Schedules scans for user.")
	Container(db, "Database", "PostgreSQL", "Stores scan and user information.")

	Container_Boundary(zap, "OWASP ZAP") {
		 Component(zap_server, "ZAP", "ZAP Server", "Does the scanning")
		 Component(zap_pds, "PDS", "PDS Server", "Communicates with SecHub server")
	}    
}

System_Ext(object_storage, "Object Storage", "The object storage")
System_Ext(user_system, "User System", "A user system or systems to scan")

Rel(user, sechub_server, "uses SecHub for security testing")
Rel(sechub_server, object_storage, "stores source code")
Rel(sechub_server, db, "stores user and scan information")
Rel(sechub_server, zap_pds, "initiates scan")
Rel(zap_pds, sechub_server, "findings")
Rel(zap_server, user_system, "scans application")
Rel(zap_pds, zap_server, "manages")
Rel(db, sechub_server, "sends information")

@enduml